<meta name="viewport" content="initial-scale=1">
<link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.3.0/pure-min.css" />
<link rel="stylesheet" href="http://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" />
<link rel="stylesheet" href="/styles/bdl.css" />

<script type="text/javascript" src="http://use.typekit.net/gan1fro.js"></script>
<script type="text/javascript">try{Typekit.load();}catch(e){}</script>